/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: attributeEnumType.proto */

#ifndef PROTOBUF_C_attributeEnumType_2eproto__INCLUDED
#define PROTOBUF_C_attributeEnumType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _AttributeEnumType {
  ATTRIBUTE_ENUM_TYPE__Actual = 0,
  ATTRIBUTE_ENUM_TYPE__Target = 1,
  ATTRIBUTE_ENUM_TYPE__MinSet = 2,
  ATTRIBUTE_ENUM_TYPE__MaxSet = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ATTRIBUTE_ENUM_TYPE)
} AttributeEnumType;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    attribute_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_attributeEnumType_2eproto__INCLUDED */
