/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: attributeEnumType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "attributeEnumType.pb-c.h"
static const ProtobufCEnumValue attribute_enum_type__enum_values_by_number[4] =
{
  { "Actual", "ATTRIBUTE_ENUM_TYPE__Actual", 0 },
  { "Target", "ATTRIBUTE_ENUM_TYPE__Target", 1 },
  { "MinSet", "ATTRIBUTE_ENUM_TYPE__MinSet", 2 },
  { "MaxSet", "ATTRIBUTE_ENUM_TYPE__MaxSet", 3 },
};
static const ProtobufCIntRange attribute_enum_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex attribute_enum_type__enum_values_by_name[4] =
{
  { "Actual", 0 },
  { "MaxSet", 3 },
  { "MinSet", 2 },
  { "Target", 1 },
};
const ProtobufCEnumDescriptor attribute_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "attributeEnumType",
  "attributeEnumType",
  "AttributeEnumType",
  "",
  4,
  attribute_enum_type__enum_values_by_number,
  4,
  attribute_enum_type__enum_values_by_name,
  1,
  attribute_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
