/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: beatHeart.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "beatHeart.pb-c.h"
void   beat_heart_req__init
                     (BeatHeartReq         *message)
{
  static const BeatHeartReq init_value = BEAT_HEART_REQ__INIT;
  *message = init_value;
}
size_t beat_heart_req__get_packed_size
                     (const BeatHeartReq *message)
{
  assert(message->base.descriptor == &beat_heart_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t beat_heart_req__pack
                     (const BeatHeartReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &beat_heart_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t beat_heart_req__pack_to_buffer
                     (const BeatHeartReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &beat_heart_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BeatHeartReq *
       beat_heart_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BeatHeartReq *)
     protobuf_c_message_unpack (&beat_heart_req__descriptor,
                                allocator, len, data);
}
void   beat_heart_req__free_unpacked
                     (BeatHeartReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &beat_heart_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   beat_heart_resp__init
                     (BeatHeartResp         *message)
{
  static const BeatHeartResp init_value = BEAT_HEART_RESP__INIT;
  *message = init_value;
}
size_t beat_heart_resp__get_packed_size
                     (const BeatHeartResp *message)
{
  assert(message->base.descriptor == &beat_heart_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t beat_heart_resp__pack
                     (const BeatHeartResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &beat_heart_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t beat_heart_resp__pack_to_buffer
                     (const BeatHeartResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &beat_heart_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BeatHeartResp *
       beat_heart_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BeatHeartResp *)
     protobuf_c_message_unpack (&beat_heart_resp__descriptor,
                                allocator, len, data);
}
void   beat_heart_resp__free_unpacked
                     (BeatHeartResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &beat_heart_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor beat_heart_req__field_descriptors[1] =
{
  {
    "csq",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(BeatHeartReq, has_csq),
    offsetof(BeatHeartReq, csq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned beat_heart_req__field_indices_by_name[] = {
  0,   /* field[0] = csq */
};
static const ProtobufCIntRange beat_heart_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor beat_heart_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "beatHeartReq",
  "BeatHeartReq",
  "BeatHeartReq",
  "",
  sizeof(BeatHeartReq),
  1,
  beat_heart_req__field_descriptors,
  beat_heart_req__field_indices_by_name,
  1,  beat_heart_req__number_ranges,
  (ProtobufCMessageInit) beat_heart_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor beat_heart_resp__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BeatHeartResp, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned beat_heart_resp__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange beat_heart_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor beat_heart_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "beatHeartResp",
  "BeatHeartResp",
  "BeatHeartResp",
  "",
  sizeof(BeatHeartResp),
  1,
  beat_heart_resp__field_descriptors,
  beat_heart_resp__field_indices_by_name,
  1,  beat_heart_resp__number_ranges,
  (ProtobufCMessageInit) beat_heart_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
