/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bootNotification.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bootNotification.pb-c.h"
void   boot_notification_req__modem_type__init
                     (BootNotificationReq__ModemType         *message)
{
  static const BootNotificationReq__ModemType init_value = BOOT_NOTIFICATION_REQ__MODEM_TYPE__INIT;
  *message = init_value;
}
void   boot_notification_req__init
                     (BootNotificationReq         *message)
{
  static const BootNotificationReq init_value = BOOT_NOTIFICATION_REQ__INIT;
  *message = init_value;
}
size_t boot_notification_req__get_packed_size
                     (const BootNotificationReq *message)
{
  assert(message->base.descriptor == &boot_notification_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t boot_notification_req__pack
                     (const BootNotificationReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &boot_notification_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t boot_notification_req__pack_to_buffer
                     (const BootNotificationReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &boot_notification_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BootNotificationReq *
       boot_notification_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BootNotificationReq *)
     protobuf_c_message_unpack (&boot_notification_req__descriptor,
                                allocator, len, data);
}
void   boot_notification_req__free_unpacked
                     (BootNotificationReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &boot_notification_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   boot_notification_resp__init
                     (BootNotificationResp         *message)
{
  static const BootNotificationResp init_value = BOOT_NOTIFICATION_RESP__INIT;
  *message = init_value;
}
size_t boot_notification_resp__get_packed_size
                     (const BootNotificationResp *message)
{
  assert(message->base.descriptor == &boot_notification_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t boot_notification_resp__pack
                     (const BootNotificationResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &boot_notification_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t boot_notification_resp__pack_to_buffer
                     (const BootNotificationResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &boot_notification_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BootNotificationResp *
       boot_notification_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BootNotificationResp *)
     protobuf_c_message_unpack (&boot_notification_resp__descriptor,
                                allocator, len, data);
}
void   boot_notification_resp__free_unpacked
                     (BootNotificationResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &boot_notification_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor boot_notification_req__modem_type__field_descriptors[2] =
{
  {
    "iccid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq__ModemType, iccid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imsi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq__ModemType, imsi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned boot_notification_req__modem_type__field_indices_by_name[] = {
  0,   /* field[0] = iccid */
  1,   /* field[1] = imsi */
};
static const ProtobufCIntRange boot_notification_req__modem_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor boot_notification_req__modem_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bootNotificationReq.modemType",
  "ModemType",
  "BootNotificationReq__ModemType",
  "",
  sizeof(BootNotificationReq__ModemType),
  2,
  boot_notification_req__modem_type__field_descriptors,
  boot_notification_req__modem_type__field_indices_by_name,
  1,  boot_notification_req__modem_type__number_ranges,
  (ProtobufCMessageInit) boot_notification_req__modem_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue boot_notification_req__boot_reason_enum_type__enum_values_by_number[8] =
{
  { "ApplicationReset", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__ApplicationReset", 0 },
  { "FirmWareUpdate", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__FirmWareUpdate", 1 },
  { "LocalReset", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__LocalReset", 2 },
  { "PowerUp", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__PowerUp", 3 },
  { "RemoteReset", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__RemoteReset", 4 },
  { "Watchdog", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__Watchdog", 5 },
  { "CommunicationTimeout", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__CommunicationTimeout", 6 },
  { "Unknown", "BOOT_NOTIFICATION_REQ__BOOT_REASON_ENUM_TYPE__Unknown", 7 },
};
static const ProtobufCIntRange boot_notification_req__boot_reason_enum_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex boot_notification_req__boot_reason_enum_type__enum_values_by_name[8] =
{
  { "ApplicationReset", 0 },
  { "CommunicationTimeout", 6 },
  { "FirmWareUpdate", 1 },
  { "LocalReset", 2 },
  { "PowerUp", 3 },
  { "RemoteReset", 4 },
  { "Unknown", 7 },
  { "Watchdog", 5 },
};
const ProtobufCEnumDescriptor boot_notification_req__boot_reason_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bootNotificationReq.bootReasonEnumType",
  "bootReasonEnumType",
  "BootNotificationReq__BootReasonEnumType",
  "",
  8,
  boot_notification_req__boot_reason_enum_type__enum_values_by_number,
  8,
  boot_notification_req__boot_reason_enum_type__enum_values_by_name,
  1,
  boot_notification_req__boot_reason_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor boot_notification_req__field_descriptors[8] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, reason),
    &boot_notification_req__boot_reason_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serialNumber",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, serialnumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendorName",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, vendorname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmwareVersion",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, firmwareversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcbID",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, pcbid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modem",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BootNotificationReq, modem),
    &boot_notification_req__modem_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned boot_notification_req__field_indices_by_name[] = {
  5,   /* field[5] = firmwareVersion */
  2,   /* field[2] = key */
  3,   /* field[3] = mode */
  7,   /* field[7] = modem */
  6,   /* field[6] = pcbID */
  0,   /* field[0] = reason */
  1,   /* field[1] = serialNumber */
  4,   /* field[4] = vendorName */
};
static const ProtobufCIntRange boot_notification_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor boot_notification_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bootNotificationReq",
  "BootNotificationReq",
  "BootNotificationReq",
  "",
  sizeof(BootNotificationReq),
  8,
  boot_notification_req__field_descriptors,
  boot_notification_req__field_indices_by_name,
  1,  boot_notification_req__number_ranges,
  (ProtobufCMessageInit) boot_notification_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue boot_notification_resp__registration_status_enum_type__enum_values_by_number[3] =
{
  { "Accepted", "BOOT_NOTIFICATION_RESP__REGISTRATION_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Pending", "BOOT_NOTIFICATION_RESP__REGISTRATION_STATUS_ENUM_TYPE__Pending", 1 },
  { "Rejected", "BOOT_NOTIFICATION_RESP__REGISTRATION_STATUS_ENUM_TYPE__Rejected", 2 },
};
static const ProtobufCIntRange boot_notification_resp__registration_status_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex boot_notification_resp__registration_status_enum_type__enum_values_by_name[3] =
{
  { "Accepted", 0 },
  { "Pending", 1 },
  { "Rejected", 2 },
};
const ProtobufCEnumDescriptor boot_notification_resp__registration_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bootNotificationResp.registrationStatusEnumType",
  "registrationStatusEnumType",
  "BootNotificationResp__RegistrationStatusEnumType",
  "",
  3,
  boot_notification_resp__registration_status_enum_type__enum_values_by_number,
  3,
  boot_notification_resp__registration_status_enum_type__enum_values_by_name,
  1,
  boot_notification_resp__registration_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor boot_notification_resp__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BootNotificationResp, status),
    &boot_notification_resp__registration_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentTime",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BootNotificationResp, currenttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BootNotificationResp, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned boot_notification_resp__field_indices_by_name[] = {
  1,   /* field[1] = currentTime */
  2,   /* field[2] = interval */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange boot_notification_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor boot_notification_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bootNotificationResp",
  "BootNotificationResp",
  "BootNotificationResp",
  "",
  sizeof(BootNotificationResp),
  3,
  boot_notification_resp__field_descriptors,
  boot_notification_resp__field_indices_by_name,
  1,  boot_notification_resp__number_ranges,
  (ProtobufCMessageInit) boot_notification_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
