/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chargingDataReport.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chargingDataReport.pb-c.h"
void   charging_data_report_req__charging_data_type__init
                     (ChargingDataReportReq__ChargingDataType         *message)
{
  static const ChargingDataReportReq__ChargingDataType init_value = CHARGING_DATA_REPORT_REQ__CHARGING_DATA_TYPE__INIT;
  *message = init_value;
}
void   charging_data_report_req__init
                     (ChargingDataReportReq         *message)
{
  static const ChargingDataReportReq init_value = CHARGING_DATA_REPORT_REQ__INIT;
  *message = init_value;
}
size_t charging_data_report_req__get_packed_size
                     (const ChargingDataReportReq *message)
{
  assert(message->base.descriptor == &charging_data_report_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t charging_data_report_req__pack
                     (const ChargingDataReportReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &charging_data_report_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t charging_data_report_req__pack_to_buffer
                     (const ChargingDataReportReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &charging_data_report_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChargingDataReportReq *
       charging_data_report_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChargingDataReportReq *)
     protobuf_c_message_unpack (&charging_data_report_req__descriptor,
                                allocator, len, data);
}
void   charging_data_report_req__free_unpacked
                     (ChargingDataReportReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &charging_data_report_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   charging_data_report_resp__init
                     (ChargingDataReportResp         *message)
{
  static const ChargingDataReportResp init_value = CHARGING_DATA_REPORT_RESP__INIT;
  *message = init_value;
}
size_t charging_data_report_resp__get_packed_size
                     (const ChargingDataReportResp *message)
{
  assert(message->base.descriptor == &charging_data_report_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t charging_data_report_resp__pack
                     (const ChargingDataReportResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &charging_data_report_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t charging_data_report_resp__pack_to_buffer
                     (const ChargingDataReportResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &charging_data_report_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChargingDataReportResp *
       charging_data_report_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChargingDataReportResp *)
     protobuf_c_message_unpack (&charging_data_report_resp__descriptor,
                                allocator, len, data);
}
void   charging_data_report_resp__free_unpacked
                     (ChargingDataReportResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &charging_data_report_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor charging_data_report_req__charging_data_type__field_descriptors[5] =
{
  {
    "connectorId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ChargingDataReportReq__ChargingDataType, connectorid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cost",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChargingDataReportReq__ChargingDataType, has_cost),
    offsetof(ChargingDataReportReq__ChargingDataType, cost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChargingDataReportReq__ChargingDataType, has_voltage),
    offsetof(ChargingDataReportReq__ChargingDataType, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChargingDataReportReq__ChargingDataType, has_current),
    offsetof(ChargingDataReportReq__ChargingDataType, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "costTime",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ChargingDataReportReq__ChargingDataType, has_costtime),
    offsetof(ChargingDataReportReq__ChargingDataType, costtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned charging_data_report_req__charging_data_type__field_indices_by_name[] = {
  0,   /* field[0] = connectorId */
  1,   /* field[1] = cost */
  4,   /* field[4] = costTime */
  3,   /* field[3] = current */
  2,   /* field[2] = voltage */
};
static const ProtobufCIntRange charging_data_report_req__charging_data_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor charging_data_report_req__charging_data_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chargingDataReportReq.chargingDataType",
  "ChargingDataType",
  "ChargingDataReportReq__ChargingDataType",
  "",
  sizeof(ChargingDataReportReq__ChargingDataType),
  5,
  charging_data_report_req__charging_data_type__field_descriptors,
  charging_data_report_req__charging_data_type__field_indices_by_name,
  1,  charging_data_report_req__charging_data_type__number_ranges,
  (ProtobufCMessageInit) charging_data_report_req__charging_data_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor charging_data_report_req__field_descriptors[2] =
{
  {
    "chargingData",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChargingDataReportReq, n_chargingdata),
    offsetof(ChargingDataReportReq, chargingdata),
    &charging_data_report_req__charging_data_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestap",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ChargingDataReportReq, timestap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned charging_data_report_req__field_indices_by_name[] = {
  0,   /* field[0] = chargingData */
  1,   /* field[1] = timestap */
};
static const ProtobufCIntRange charging_data_report_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor charging_data_report_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chargingDataReportReq",
  "ChargingDataReportReq",
  "ChargingDataReportReq",
  "",
  sizeof(ChargingDataReportReq),
  2,
  charging_data_report_req__field_descriptors,
  charging_data_report_req__field_indices_by_name,
  1,  charging_data_report_req__number_ranges,
  (ProtobufCMessageInit) charging_data_report_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define charging_data_report_resp__field_descriptors NULL
#define charging_data_report_resp__field_indices_by_name NULL
#define charging_data_report_resp__number_ranges NULL
const ProtobufCMessageDescriptor charging_data_report_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chargingDataReportResp",
  "ChargingDataReportResp",
  "ChargingDataReportResp",
  "",
  sizeof(ChargingDataReportResp),
  0,
  charging_data_report_resp__field_descriptors,
  charging_data_report_resp__field_indices_by_name,
  0,  charging_data_report_resp__number_ranges,
  (ProtobufCMessageInit) charging_data_report_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
