/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: componentType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "componentType.pb-c.h"
void   component_type__init
                     (ComponentType         *message)
{
  static const ComponentType init_value = COMPONENT_TYPE__INIT;
  *message = init_value;
}
size_t component_type__get_packed_size
                     (const ComponentType *message)
{
  assert(message->base.descriptor == &component_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t component_type__pack
                     (const ComponentType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &component_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t component_type__pack_to_buffer
                     (const ComponentType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &component_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ComponentType *
       component_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ComponentType *)
     protobuf_c_message_unpack (&component_type__descriptor,
                                allocator, len, data);
}
void   component_type__free_unpacked
                     (ComponentType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &component_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor component_type__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ComponentType, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ComponentType, instance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connector",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ComponentType, has_connector),
    offsetof(ComponentType, connector),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned component_type__field_indices_by_name[] = {
  2,   /* field[2] = connector */
  1,   /* field[1] = instance */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange component_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor component_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "componentType",
  "ComponentType",
  "ComponentType",
  "",
  sizeof(ComponentType),
  3,
  component_type__field_descriptors,
  component_type__field_indices_by_name,
  1,  component_type__number_ranges,
  (ProtobufCMessageInit) component_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
