/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: componentType.proto */

#ifndef PROTOBUF_C_componentType_2eproto__INCLUDED
#define PROTOBUF_C_componentType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ComponentType ComponentType;


/* --- enums --- */


/* --- messages --- */

struct  _ComponentType
{
  ProtobufCMessage base;
  char *name;
  char *instance;
  protobuf_c_boolean has_connector;
  int32_t connector;
};
#define COMPONENT_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&component_type__descriptor) \
    , NULL, NULL, 0, 0 }


/* ComponentType methods */
void   component_type__init
                     (ComponentType         *message);
size_t component_type__get_packed_size
                     (const ComponentType   *message);
size_t component_type__pack
                     (const ComponentType   *message,
                      uint8_t             *out);
size_t component_type__pack_to_buffer
                     (const ComponentType   *message,
                      ProtobufCBuffer     *buffer);
ComponentType *
       component_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   component_type__free_unpacked
                     (ComponentType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ComponentType_Closure)
                 (const ComponentType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor component_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_componentType_2eproto__INCLUDED */
