/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: costUpdated.proto */

#ifndef PROTOBUF_C_costUpdated_2eproto__INCLUDED
#define PROTOBUF_C_costUpdated_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CostUpdatedReq CostUpdatedReq;
typedef struct _CostUpdatedResp CostUpdatedResp;


/* --- enums --- */

typedef enum _CostUpdatedResp__CostUpdatedStatusEnumType {
  COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE__Accepted = 0,
  COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE__Rejected = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE)
} CostUpdatedResp__CostUpdatedStatusEnumType;

/* --- messages --- */

struct  _CostUpdatedReq
{
  ProtobufCMessage base;
  protobuf_c_boolean has_totalcost;
  uint32_t totalcost;
  protobuf_c_boolean has_totaltime;
  uint32_t totaltime;
  ProtobufCBinaryData transactionid;
};
#define COST_UPDATED_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cost_updated_req__descriptor) \
    , 0, 0, 0, 0, {0,NULL} }


struct  _CostUpdatedResp
{
  ProtobufCMessage base;
  CostUpdatedResp__CostUpdatedStatusEnumType status;
};
#define COST_UPDATED_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cost_updated_resp__descriptor) \
    , COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE__Accepted }


/* CostUpdatedReq methods */
void   cost_updated_req__init
                     (CostUpdatedReq         *message);
size_t cost_updated_req__get_packed_size
                     (const CostUpdatedReq   *message);
size_t cost_updated_req__pack
                     (const CostUpdatedReq   *message,
                      uint8_t             *out);
size_t cost_updated_req__pack_to_buffer
                     (const CostUpdatedReq   *message,
                      ProtobufCBuffer     *buffer);
CostUpdatedReq *
       cost_updated_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cost_updated_req__free_unpacked
                     (CostUpdatedReq *message,
                      ProtobufCAllocator *allocator);
/* CostUpdatedResp methods */
void   cost_updated_resp__init
                     (CostUpdatedResp         *message);
size_t cost_updated_resp__get_packed_size
                     (const CostUpdatedResp   *message);
size_t cost_updated_resp__pack
                     (const CostUpdatedResp   *message,
                      uint8_t             *out);
size_t cost_updated_resp__pack_to_buffer
                     (const CostUpdatedResp   *message,
                      ProtobufCBuffer     *buffer);
CostUpdatedResp *
       cost_updated_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cost_updated_resp__free_unpacked
                     (CostUpdatedResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CostUpdatedReq_Closure)
                 (const CostUpdatedReq *message,
                  void *closure_data);
typedef void (*CostUpdatedResp_Closure)
                 (const CostUpdatedResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cost_updated_req__descriptor;
extern const ProtobufCMessageDescriptor cost_updated_resp__descriptor;
extern const ProtobufCEnumDescriptor    cost_updated_resp__cost_updated_status_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_costUpdated_2eproto__INCLUDED */
