/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: costUpdated.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "costUpdated.pb-c.h"
void   cost_updated_req__init
                     (CostUpdatedReq         *message)
{
  static const CostUpdatedReq init_value = COST_UPDATED_REQ__INIT;
  *message = init_value;
}
size_t cost_updated_req__get_packed_size
                     (const CostUpdatedReq *message)
{
  assert(message->base.descriptor == &cost_updated_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cost_updated_req__pack
                     (const CostUpdatedReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cost_updated_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cost_updated_req__pack_to_buffer
                     (const CostUpdatedReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cost_updated_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CostUpdatedReq *
       cost_updated_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CostUpdatedReq *)
     protobuf_c_message_unpack (&cost_updated_req__descriptor,
                                allocator, len, data);
}
void   cost_updated_req__free_unpacked
                     (CostUpdatedReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cost_updated_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cost_updated_resp__init
                     (CostUpdatedResp         *message)
{
  static const CostUpdatedResp init_value = COST_UPDATED_RESP__INIT;
  *message = init_value;
}
size_t cost_updated_resp__get_packed_size
                     (const CostUpdatedResp *message)
{
  assert(message->base.descriptor == &cost_updated_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cost_updated_resp__pack
                     (const CostUpdatedResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cost_updated_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cost_updated_resp__pack_to_buffer
                     (const CostUpdatedResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cost_updated_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CostUpdatedResp *
       cost_updated_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CostUpdatedResp *)
     protobuf_c_message_unpack (&cost_updated_resp__descriptor,
                                allocator, len, data);
}
void   cost_updated_resp__free_unpacked
                     (CostUpdatedResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cost_updated_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cost_updated_req__field_descriptors[3] =
{
  {
    "totalCost",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CostUpdatedReq, has_totalcost),
    offsetof(CostUpdatedReq, totalcost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalTime",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CostUpdatedReq, has_totaltime),
    offsetof(CostUpdatedReq, totaltime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionID",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CostUpdatedReq, transactionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cost_updated_req__field_indices_by_name[] = {
  0,   /* field[0] = totalCost */
  1,   /* field[1] = totalTime */
  2,   /* field[2] = transactionID */
};
static const ProtobufCIntRange cost_updated_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cost_updated_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "costUpdatedReq",
  "CostUpdatedReq",
  "CostUpdatedReq",
  "",
  sizeof(CostUpdatedReq),
  3,
  cost_updated_req__field_descriptors,
  cost_updated_req__field_indices_by_name,
  1,  cost_updated_req__number_ranges,
  (ProtobufCMessageInit) cost_updated_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cost_updated_resp__cost_updated_status_enum_type__enum_values_by_number[2] =
{
  { "Accepted", "COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Rejected", "COST_UPDATED_RESP__COST_UPDATED_STATUS_ENUM_TYPE__Rejected", 1 },
};
static const ProtobufCIntRange cost_updated_resp__cost_updated_status_enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex cost_updated_resp__cost_updated_status_enum_type__enum_values_by_name[2] =
{
  { "Accepted", 0 },
  { "Rejected", 1 },
};
const ProtobufCEnumDescriptor cost_updated_resp__cost_updated_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "costUpdatedResp.costUpdatedStatusEnumType",
  "costUpdatedStatusEnumType",
  "CostUpdatedResp__CostUpdatedStatusEnumType",
  "",
  2,
  cost_updated_resp__cost_updated_status_enum_type__enum_values_by_number,
  2,
  cost_updated_resp__cost_updated_status_enum_type__enum_values_by_name,
  1,
  cost_updated_resp__cost_updated_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cost_updated_resp__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CostUpdatedResp, status),
    &cost_updated_resp__cost_updated_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cost_updated_resp__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange cost_updated_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cost_updated_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "costUpdatedResp",
  "CostUpdatedResp",
  "CostUpdatedResp",
  "",
  sizeof(CostUpdatedResp),
  1,
  cost_updated_resp__field_descriptors,
  cost_updated_resp__field_indices_by_name,
  1,  cost_updated_resp__number_ranges,
  (ProtobufCMessageInit) cost_updated_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
