/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: getVariables.proto */

#ifndef PROTOBUF_C_getVariables_2eproto__INCLUDED
#define PROTOBUF_C_getVariables_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "getVariableDataType.pb-c.h"
#include "getVariableResultType.pb-c.h"

typedef struct _GetVariableReq GetVariableReq;
typedef struct _GetVariableResp GetVariableResp;


/* --- enums --- */


/* --- messages --- */

struct  _GetVariableReq
{
  ProtobufCMessage base;
  size_t n_getvariablesdata;
  GetVariableDataType **getvariablesdata;
};
#define GET_VARIABLE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_variable_req__descriptor) \
    , 0,NULL }


struct  _GetVariableResp
{
  ProtobufCMessage base;
  size_t n_getvariables;
  GetVariableResultType **getvariables;
};
#define GET_VARIABLE_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&get_variable_resp__descriptor) \
    , 0,NULL }


/* GetVariableReq methods */
void   get_variable_req__init
                     (GetVariableReq         *message);
size_t get_variable_req__get_packed_size
                     (const GetVariableReq   *message);
size_t get_variable_req__pack
                     (const GetVariableReq   *message,
                      uint8_t             *out);
size_t get_variable_req__pack_to_buffer
                     (const GetVariableReq   *message,
                      ProtobufCBuffer     *buffer);
GetVariableReq *
       get_variable_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_variable_req__free_unpacked
                     (GetVariableReq *message,
                      ProtobufCAllocator *allocator);
/* GetVariableResp methods */
void   get_variable_resp__init
                     (GetVariableResp         *message);
size_t get_variable_resp__get_packed_size
                     (const GetVariableResp   *message);
size_t get_variable_resp__pack
                     (const GetVariableResp   *message,
                      uint8_t             *out);
size_t get_variable_resp__pack_to_buffer
                     (const GetVariableResp   *message,
                      ProtobufCBuffer     *buffer);
GetVariableResp *
       get_variable_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   get_variable_resp__free_unpacked
                     (GetVariableResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*GetVariableReq_Closure)
                 (const GetVariableReq *message,
                  void *closure_data);
typedef void (*GetVariableResp_Closure)
                 (const GetVariableResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor get_variable_req__descriptor;
extern const ProtobufCMessageDescriptor get_variable_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_getVariables_2eproto__INCLUDED */
