/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: getVariableResultType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "getVariableResultType.pb-c.h"
void   get_variable_result_type__init
                     (GetVariableResultType         *message)
{
  static const GetVariableResultType init_value = GET_VARIABLE_RESULT_TYPE__INIT;
  *message = init_value;
}
size_t get_variable_result_type__get_packed_size
                     (const GetVariableResultType *message)
{
  assert(message->base.descriptor == &get_variable_result_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_variable_result_type__pack
                     (const GetVariableResultType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_variable_result_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_variable_result_type__pack_to_buffer
                     (const GetVariableResultType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_variable_result_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetVariableResultType *
       get_variable_result_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetVariableResultType *)
     protobuf_c_message_unpack (&get_variable_result_type__descriptor,
                                allocator, len, data);
}
void   get_variable_result_type__free_unpacked
                     (GetVariableResultType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_variable_result_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor get_variable_result_type__field_descriptors[4] =
{
  {
    "attributeType",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(GetVariableResultType, has_attributetype),
    offsetof(GetVariableResultType, attributetype),
    &attribute_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributeValue",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetVariableResultType, attributevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GetVariableResultType, component),
    &component_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "variable",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GetVariableResultType, variable),
    &variable_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_variable_result_type__field_indices_by_name[] = {
  0,   /* field[0] = attributeType */
  1,   /* field[1] = attributeValue */
  2,   /* field[2] = component */
  3,   /* field[3] = variable */
};
static const ProtobufCIntRange get_variable_result_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor get_variable_result_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "getVariableResultType",
  "GetVariableResultType",
  "GetVariableResultType",
  "",
  sizeof(GetVariableResultType),
  4,
  get_variable_result_type__field_descriptors,
  get_variable_result_type__field_indices_by_name,
  1,  get_variable_result_type__number_ranges,
  (ProtobufCMessageInit) get_variable_result_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
