/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IDTokenType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "IDTokenType.pb-c.h"
void   idtoken_type__init
                     (IDTokenType         *message)
{
  static const IDTokenType init_value = IDTOKEN_TYPE__INIT;
  *message = init_value;
}
size_t idtoken_type__get_packed_size
                     (const IDTokenType *message)
{
  assert(message->base.descriptor == &idtoken_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t idtoken_type__pack
                     (const IDTokenType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &idtoken_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t idtoken_type__pack_to_buffer
                     (const IDTokenType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &idtoken_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IDTokenType *
       idtoken_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IDTokenType *)
     protobuf_c_message_unpack (&idtoken_type__descriptor,
                                allocator, len, data);
}
void   idtoken_type__free_unpacked
                     (IDTokenType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &idtoken_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue idtoken_type__idtoken_enum_type__enum_values_by_number[7] =
{
  { "Central", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__Central", 0 },
  { "eMAID", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__eMAID", 1 },
  { "ISO14443", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__ISO14443", 2 },
  { "Local", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__Local", 3 },
  { "PinCode", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__PinCode", 4 },
  { "ISO15693", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__ISO15693", 5 },
  { "NoAuthorization", "IDTOKEN_TYPE__IDTOKEN_ENUM_TYPE__NoAuthorization", 6 },
};
static const ProtobufCIntRange idtoken_type__idtoken_enum_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex idtoken_type__idtoken_enum_type__enum_values_by_name[7] =
{
  { "Central", 0 },
  { "ISO14443", 2 },
  { "ISO15693", 5 },
  { "Local", 3 },
  { "NoAuthorization", 6 },
  { "PinCode", 4 },
  { "eMAID", 1 },
};
const ProtobufCEnumDescriptor idtoken_type__idtoken_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IDTokenType.IDTokenEnumType",
  "IDTokenEnumType",
  "IDTokenType__IDTokenEnumType",
  "",
  7,
  idtoken_type__idtoken_enum_type__enum_values_by_number,
  7,
  idtoken_type__idtoken_enum_type__enum_values_by_name,
  1,
  idtoken_type__idtoken_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor idtoken_type__field_descriptors[2] =
{
  {
    "idToken",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(IDTokenType, idtoken),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(IDTokenType, type),
    &idtoken_type__idtoken_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned idtoken_type__field_indices_by_name[] = {
  0,   /* field[0] = idToken */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange idtoken_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor idtoken_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IDTokenType",
  "IDTokenType",
  "IDTokenType",
  "",
  sizeof(IDTokenType),
  2,
  idtoken_type__field_descriptors,
  idtoken_type__field_indices_by_name,
  1,  idtoken_type__number_ranges,
  (ProtobufCMessageInit) idtoken_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
