/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IDTokenInfoType.proto */

#ifndef PROTOBUF_C_IDTokenInfoType_2eproto__INCLUDED
#define PROTOBUF_C_IDTokenInfoType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IDTokenType.pb-c.h"

typedef struct _IDTokenInfoType IDTokenInfoType;
typedef struct _IDTokenInfoType__PersonalContentType IDTokenInfoType__PersonalContentType;


/* --- enums --- */

typedef enum _IDTokenInfoType__AuthorizationStatusEnumType {
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Accepted = 0,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Blocked = 1,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Expired = 2,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Invalid = 3,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__NoCredit = 4,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__NotAllowedTypeEVSE = 5,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__NotAtThisLocation = 6,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__NotAtThisTime = 7,
  IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Unknown = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE)
} IDTokenInfoType__AuthorizationStatusEnumType;

/* --- messages --- */

struct  _IDTokenInfoType__PersonalContentType
{
  ProtobufCMessage base;
  protobuf_c_boolean has_balance;
  uint32_t balance;
};
#define IDTOKEN_INFO_TYPE__PERSONAL_CONTENT_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&idtoken_info_type__personal_content_type__descriptor) \
    , 0, 0 }


struct  _IDTokenInfoType
{
  ProtobufCMessage base;
  IDTokenInfoType__AuthorizationStatusEnumType status;
  IDTokenType *groupidtoken;
  IDTokenInfoType__PersonalContentType *personal;
};
#define IDTOKEN_INFO_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&idtoken_info_type__descriptor) \
    , IDTOKEN_INFO_TYPE__AUTHORIZATION_STATUS_ENUM_TYPE__Accepted, NULL, NULL }


/* IDTokenInfoType__PersonalContentType methods */
void   idtoken_info_type__personal_content_type__init
                     (IDTokenInfoType__PersonalContentType         *message);
/* IDTokenInfoType methods */
void   idtoken_info_type__init
                     (IDTokenInfoType         *message);
size_t idtoken_info_type__get_packed_size
                     (const IDTokenInfoType   *message);
size_t idtoken_info_type__pack
                     (const IDTokenInfoType   *message,
                      uint8_t             *out);
size_t idtoken_info_type__pack_to_buffer
                     (const IDTokenInfoType   *message,
                      ProtobufCBuffer     *buffer);
IDTokenInfoType *
       idtoken_info_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   idtoken_info_type__free_unpacked
                     (IDTokenInfoType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IDTokenInfoType__PersonalContentType_Closure)
                 (const IDTokenInfoType__PersonalContentType *message,
                  void *closure_data);
typedef void (*IDTokenInfoType_Closure)
                 (const IDTokenInfoType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor idtoken_info_type__descriptor;
extern const ProtobufCMessageDescriptor idtoken_info_type__personal_content_type__descriptor;
extern const ProtobufCEnumDescriptor    idtoken_info_type__authorization_status_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_IDTokenInfoType_2eproto__INCLUDED */
