/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: notifyEvent.proto */

#ifndef PROTOBUF_C_notifyEvent_2eproto__INCLUDED
#define PROTOBUF_C_notifyEvent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "componentType.pb-c.h"
#include "variableType.pb-c.h"

typedef struct _NotifyEventReq NotifyEventReq;
typedef struct _NotifyEventResp NotifyEventResp;


/* --- enums --- */


/* --- messages --- */

struct  _NotifyEventReq
{
  ProtobufCMessage base;
  ProtobufCBinaryData timestamp;
  char *actualvalue;
  ComponentType *component;
  VariableType *variable;
};
#define NOTIFY_EVENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notify_event_req__descriptor) \
    , {0,NULL}, NULL, NULL, NULL }


struct  _NotifyEventResp
{
  ProtobufCMessage base;
};
#define NOTIFY_EVENT_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notify_event_resp__descriptor) \
     }


/* NotifyEventReq methods */
void   notify_event_req__init
                     (NotifyEventReq         *message);
size_t notify_event_req__get_packed_size
                     (const NotifyEventReq   *message);
size_t notify_event_req__pack
                     (const NotifyEventReq   *message,
                      uint8_t             *out);
size_t notify_event_req__pack_to_buffer
                     (const NotifyEventReq   *message,
                      ProtobufCBuffer     *buffer);
NotifyEventReq *
       notify_event_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notify_event_req__free_unpacked
                     (NotifyEventReq *message,
                      ProtobufCAllocator *allocator);
/* NotifyEventResp methods */
void   notify_event_resp__init
                     (NotifyEventResp         *message);
size_t notify_event_resp__get_packed_size
                     (const NotifyEventResp   *message);
size_t notify_event_resp__pack
                     (const NotifyEventResp   *message,
                      uint8_t             *out);
size_t notify_event_resp__pack_to_buffer
                     (const NotifyEventResp   *message,
                      ProtobufCBuffer     *buffer);
NotifyEventResp *
       notify_event_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notify_event_resp__free_unpacked
                     (NotifyEventResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NotifyEventReq_Closure)
                 (const NotifyEventReq *message,
                  void *closure_data);
typedef void (*NotifyEventResp_Closure)
                 (const NotifyEventResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor notify_event_req__descriptor;
extern const ProtobufCMessageDescriptor notify_event_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_notifyEvent_2eproto__INCLUDED */
