/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: notifyEvent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "notifyEvent.pb-c.h"
void   notify_event_req__init
                     (NotifyEventReq         *message)
{
  static const NotifyEventReq init_value = NOTIFY_EVENT_REQ__INIT;
  *message = init_value;
}
size_t notify_event_req__get_packed_size
                     (const NotifyEventReq *message)
{
  assert(message->base.descriptor == &notify_event_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_event_req__pack
                     (const NotifyEventReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_event_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_event_req__pack_to_buffer
                     (const NotifyEventReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_event_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyEventReq *
       notify_event_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyEventReq *)
     protobuf_c_message_unpack (&notify_event_req__descriptor,
                                allocator, len, data);
}
void   notify_event_req__free_unpacked
                     (NotifyEventReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_event_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   notify_event_resp__init
                     (NotifyEventResp         *message)
{
  static const NotifyEventResp init_value = NOTIFY_EVENT_RESP__INIT;
  *message = init_value;
}
size_t notify_event_resp__get_packed_size
                     (const NotifyEventResp *message)
{
  assert(message->base.descriptor == &notify_event_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify_event_resp__pack
                     (const NotifyEventResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify_event_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify_event_resp__pack_to_buffer
                     (const NotifyEventResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify_event_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotifyEventResp *
       notify_event_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotifyEventResp *)
     protobuf_c_message_unpack (&notify_event_resp__descriptor,
                                allocator, len, data);
}
void   notify_event_resp__free_unpacked
                     (NotifyEventResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify_event_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor notify_event_req__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(NotifyEventReq, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actualValue",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NotifyEventReq, actualvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyEventReq, component),
    &component_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "variable",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(NotifyEventReq, variable),
    &variable_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify_event_req__field_indices_by_name[] = {
  1,   /* field[1] = actualValue */
  2,   /* field[2] = component */
  0,   /* field[0] = timestamp */
  3,   /* field[3] = variable */
};
static const ProtobufCIntRange notify_event_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor notify_event_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "notifyEventReq",
  "NotifyEventReq",
  "NotifyEventReq",
  "",
  sizeof(NotifyEventReq),
  4,
  notify_event_req__field_descriptors,
  notify_event_req__field_indices_by_name,
  1,  notify_event_req__number_ranges,
  (ProtobufCMessageInit) notify_event_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define notify_event_resp__field_descriptors NULL
#define notify_event_resp__field_indices_by_name NULL
#define notify_event_resp__number_ranges NULL
const ProtobufCMessageDescriptor notify_event_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "notifyEventResp",
  "NotifyEventResp",
  "NotifyEventResp",
  "",
  sizeof(NotifyEventResp),
  0,
  notify_event_resp__field_descriptors,
  notify_event_resp__field_indices_by_name,
  0,  notify_event_resp__number_ranges,
  (ProtobufCMessageInit) notify_event_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
