/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setVariableResultType.proto */

#ifndef PROTOBUF_C_setVariableResultType_2eproto__INCLUDED
#define PROTOBUF_C_setVariableResultType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "attributeEnumType.pb-c.h"
#include "componentType.pb-c.h"
#include "variableType.pb-c.h"

typedef struct _SetVariableResultType SetVariableResultType;


/* --- enums --- */

typedef enum _SetVariableResultType__SetVariableStatusEnumType {
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__Accepted = 0,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__Rejected = 1,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__InvalidValue = 2,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknownComponent = 3,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknownVariable = 4,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknowAttributeType = 5,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__OutOfRange = 6,
  SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__RebootRequired = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE)
} SetVariableResultType__SetVariableStatusEnumType;

/* --- messages --- */

struct  _SetVariableResultType
{
  ProtobufCMessage base;
  SetVariableResultType__SetVariableStatusEnumType attributestatus;
  protobuf_c_boolean has_attributetype;
  AttributeEnumType attributetype;
  ComponentType *component;
  VariableType *variable;
};
#define SET_VARIABLE_RESULT_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_variable_result_type__descriptor) \
    , SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__Accepted, 0, ATTRIBUTE_ENUM_TYPE__Actual, NULL, NULL }


/* SetVariableResultType methods */
void   set_variable_result_type__init
                     (SetVariableResultType         *message);
size_t set_variable_result_type__get_packed_size
                     (const SetVariableResultType   *message);
size_t set_variable_result_type__pack
                     (const SetVariableResultType   *message,
                      uint8_t             *out);
size_t set_variable_result_type__pack_to_buffer
                     (const SetVariableResultType   *message,
                      ProtobufCBuffer     *buffer);
SetVariableResultType *
       set_variable_result_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_variable_result_type__free_unpacked
                     (SetVariableResultType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SetVariableResultType_Closure)
                 (const SetVariableResultType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor set_variable_result_type__descriptor;
extern const ProtobufCEnumDescriptor    set_variable_result_type__set_variable_status_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_setVariableResultType_2eproto__INCLUDED */
