/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setVariableDataType.proto */

#ifndef PROTOBUF_C_setVariableDataType_2eproto__INCLUDED
#define PROTOBUF_C_setVariableDataType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "componentType.pb-c.h"
#include "variableType.pb-c.h"
#include "attributeEnumType.pb-c.h"

typedef struct _SetVariableDataType SetVariableDataType;


/* --- enums --- */


/* --- messages --- */

struct  _SetVariableDataType
{
  ProtobufCMessage base;
  protobuf_c_boolean has_attributetype;
  AttributeEnumType attributetype;
  char *attributevalue;
  ComponentType *component;
  VariableType *variable;
};
#define SET_VARIABLE_DATA_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&set_variable_data_type__descriptor) \
    , 0, ATTRIBUTE_ENUM_TYPE__Actual, NULL, NULL, NULL }


/* SetVariableDataType methods */
void   set_variable_data_type__init
                     (SetVariableDataType         *message);
size_t set_variable_data_type__get_packed_size
                     (const SetVariableDataType   *message);
size_t set_variable_data_type__pack
                     (const SetVariableDataType   *message,
                      uint8_t             *out);
size_t set_variable_data_type__pack_to_buffer
                     (const SetVariableDataType   *message,
                      ProtobufCBuffer     *buffer);
SetVariableDataType *
       set_variable_data_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   set_variable_data_type__free_unpacked
                     (SetVariableDataType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SetVariableDataType_Closure)
                 (const SetVariableDataType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor set_variable_data_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_setVariableDataType_2eproto__INCLUDED */
