/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setVariableDataType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "setVariableDataType.pb-c.h"
void   set_variable_data_type__init
                     (SetVariableDataType         *message)
{
  static const SetVariableDataType init_value = SET_VARIABLE_DATA_TYPE__INIT;
  *message = init_value;
}
size_t set_variable_data_type__get_packed_size
                     (const SetVariableDataType *message)
{
  assert(message->base.descriptor == &set_variable_data_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_variable_data_type__pack
                     (const SetVariableDataType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_variable_data_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_variable_data_type__pack_to_buffer
                     (const SetVariableDataType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_variable_data_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetVariableDataType *
       set_variable_data_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetVariableDataType *)
     protobuf_c_message_unpack (&set_variable_data_type__descriptor,
                                allocator, len, data);
}
void   set_variable_data_type__free_unpacked
                     (SetVariableDataType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_variable_data_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor set_variable_data_type__field_descriptors[4] =
{
  {
    "attributeType",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SetVariableDataType, has_attributetype),
    offsetof(SetVariableDataType, attributetype),
    &attribute_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributeValue",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SetVariableDataType, attributevalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SetVariableDataType, component),
    &component_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "variable",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SetVariableDataType, variable),
    &variable_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_variable_data_type__field_indices_by_name[] = {
  0,   /* field[0] = attributeType */
  1,   /* field[1] = attributeValue */
  2,   /* field[2] = component */
  3,   /* field[3] = variable */
};
static const ProtobufCIntRange set_variable_data_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor set_variable_data_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "setVariableDataType",
  "SetVariableDataType",
  "SetVariableDataType",
  "",
  sizeof(SetVariableDataType),
  4,
  set_variable_data_type__field_descriptors,
  set_variable_data_type__field_indices_by_name,
  1,  set_variable_data_type__number_ranges,
  (ProtobufCMessageInit) set_variable_data_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
