/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setVariableResultType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "setVariableResultType.pb-c.h"
void   set_variable_result_type__init
                     (SetVariableResultType         *message)
{
  static const SetVariableResultType init_value = SET_VARIABLE_RESULT_TYPE__INIT;
  *message = init_value;
}
size_t set_variable_result_type__get_packed_size
                     (const SetVariableResultType *message)
{
  assert(message->base.descriptor == &set_variable_result_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_variable_result_type__pack
                     (const SetVariableResultType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_variable_result_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_variable_result_type__pack_to_buffer
                     (const SetVariableResultType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_variable_result_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetVariableResultType *
       set_variable_result_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetVariableResultType *)
     protobuf_c_message_unpack (&set_variable_result_type__descriptor,
                                allocator, len, data);
}
void   set_variable_result_type__free_unpacked
                     (SetVariableResultType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &set_variable_result_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue set_variable_result_type__set_variable_status_enum_type__enum_values_by_number[8] =
{
  { "Accepted", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Rejected", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__Rejected", 1 },
  { "InvalidValue", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__InvalidValue", 2 },
  { "UnknownComponent", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknownComponent", 3 },
  { "UnknownVariable", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknownVariable", 4 },
  { "UnknowAttributeType", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__UnknowAttributeType", 5 },
  { "OutOfRange", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__OutOfRange", 6 },
  { "RebootRequired", "SET_VARIABLE_RESULT_TYPE__SET_VARIABLE_STATUS_ENUM_TYPE__RebootRequired", 7 },
};
static const ProtobufCIntRange set_variable_result_type__set_variable_status_enum_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex set_variable_result_type__set_variable_status_enum_type__enum_values_by_name[8] =
{
  { "Accepted", 0 },
  { "InvalidValue", 2 },
  { "OutOfRange", 6 },
  { "RebootRequired", 7 },
  { "Rejected", 1 },
  { "UnknowAttributeType", 5 },
  { "UnknownComponent", 3 },
  { "UnknownVariable", 4 },
};
const ProtobufCEnumDescriptor set_variable_result_type__set_variable_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "setVariableResultType.setVariableStatusEnumType",
  "setVariableStatusEnumType",
  "SetVariableResultType__SetVariableStatusEnumType",
  "",
  8,
  set_variable_result_type__set_variable_status_enum_type__enum_values_by_number,
  8,
  set_variable_result_type__set_variable_status_enum_type__enum_values_by_name,
  1,
  set_variable_result_type__set_variable_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor set_variable_result_type__field_descriptors[4] =
{
  {
    "attributeStatus",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SetVariableResultType, attributestatus),
    &set_variable_result_type__set_variable_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributeType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SetVariableResultType, has_attributetype),
    offsetof(SetVariableResultType, attributetype),
    &attribute_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SetVariableResultType, component),
    &component_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "variable",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SetVariableResultType, variable),
    &variable_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_variable_result_type__field_indices_by_name[] = {
  0,   /* field[0] = attributeStatus */
  1,   /* field[1] = attributeType */
  2,   /* field[2] = component */
  3,   /* field[3] = variable */
};
static const ProtobufCIntRange set_variable_result_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor set_variable_result_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "setVariableResultType",
  "SetVariableResultType",
  "SetVariableResultType",
  "",
  sizeof(SetVariableResultType),
  4,
  set_variable_result_type__field_descriptors,
  set_variable_result_type__field_indices_by_name,
  1,  set_variable_result_type__number_ranges,
  (ProtobufCMessageInit) set_variable_result_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
