/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: startTransaction.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "startTransaction.pb-c.h"
void   start_transaction_req__charging_profile_type__init
                     (StartTransactionReq__ChargingProfileType         *message)
{
  static const StartTransactionReq__ChargingProfileType init_value = START_TRANSACTION_REQ__CHARGING_PROFILE_TYPE__INIT;
  *message = init_value;
}
void   start_transaction_req__init
                     (StartTransactionReq         *message)
{
  static const StartTransactionReq init_value = START_TRANSACTION_REQ__INIT;
  *message = init_value;
}
size_t start_transaction_req__get_packed_size
                     (const StartTransactionReq *message)
{
  assert(message->base.descriptor == &start_transaction_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_transaction_req__pack
                     (const StartTransactionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_transaction_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_transaction_req__pack_to_buffer
                     (const StartTransactionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_transaction_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartTransactionReq *
       start_transaction_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartTransactionReq *)
     protobuf_c_message_unpack (&start_transaction_req__descriptor,
                                allocator, len, data);
}
void   start_transaction_req__free_unpacked
                     (StartTransactionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_transaction_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   start_transaction_resp__init
                     (StartTransactionResp         *message)
{
  static const StartTransactionResp init_value = START_TRANSACTION_RESP__INIT;
  *message = init_value;
}
size_t start_transaction_resp__get_packed_size
                     (const StartTransactionResp *message)
{
  assert(message->base.descriptor == &start_transaction_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t start_transaction_resp__pack
                     (const StartTransactionResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &start_transaction_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t start_transaction_resp__pack_to_buffer
                     (const StartTransactionResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &start_transaction_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StartTransactionResp *
       start_transaction_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StartTransactionResp *)
     protobuf_c_message_unpack (&start_transaction_resp__descriptor,
                                allocator, len, data);
}
void   start_transaction_resp__free_unpacked
                     (StartTransactionResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &start_transaction_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor start_transaction_req__charging_profile_type__field_descriptors[3] =
{
  {
    "chargeMode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartTransactionReq__ChargingProfileType, chargemode),
    &start_transaction_req__charge_mode_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartTransactionReq__ChargingProfileType, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "powerLimit",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StartTransactionReq__ChargingProfileType, has_powerlimit),
    offsetof(StartTransactionReq__ChargingProfileType, powerlimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_transaction_req__charging_profile_type__field_indices_by_name[] = {
  0,   /* field[0] = chargeMode */
  2,   /* field[2] = powerLimit */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange start_transaction_req__charging_profile_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor start_transaction_req__charging_profile_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "startTransactionReq.chargingProfileType",
  "ChargingProfileType",
  "StartTransactionReq__ChargingProfileType",
  "",
  sizeof(StartTransactionReq__ChargingProfileType),
  3,
  start_transaction_req__charging_profile_type__field_descriptors,
  start_transaction_req__charging_profile_type__field_indices_by_name,
  1,  start_transaction_req__charging_profile_type__number_ranges,
  (ProtobufCMessageInit) start_transaction_req__charging_profile_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue start_transaction_req__charge_mode_enum_type__enum_values_by_number[3] =
{
  { "ChargeByHour", "START_TRANSACTION_REQ__CHARGE_MODE_ENUM_TYPE__ChargeByHour", 0 },
  { "ChargeByMoney", "START_TRANSACTION_REQ__CHARGE_MODE_ENUM_TYPE__ChargeByMoney", 1 },
  { "ChargeByEnergy", "START_TRANSACTION_REQ__CHARGE_MODE_ENUM_TYPE__ChargeByEnergy", 2 },
};
static const ProtobufCIntRange start_transaction_req__charge_mode_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex start_transaction_req__charge_mode_enum_type__enum_values_by_name[3] =
{
  { "ChargeByEnergy", 2 },
  { "ChargeByHour", 0 },
  { "ChargeByMoney", 1 },
};
const ProtobufCEnumDescriptor start_transaction_req__charge_mode_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "startTransactionReq.chargeModeEnumType",
  "chargeModeEnumType",
  "StartTransactionReq__ChargeModeEnumType",
  "",
  3,
  start_transaction_req__charge_mode_enum_type__enum_values_by_number,
  3,
  start_transaction_req__charge_mode_enum_type__enum_values_by_name,
  1,
  start_transaction_req__charge_mode_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor start_transaction_req__field_descriptors[3] =
{
  {
    "connectorId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StartTransactionReq, connectorid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IDToken",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartTransactionReq, idtoken),
    &idtoken_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chargingProfile",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StartTransactionReq, chargingprofile),
    &start_transaction_req__charging_profile_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_transaction_req__field_indices_by_name[] = {
  1,   /* field[1] = IDToken */
  2,   /* field[2] = chargingProfile */
  0,   /* field[0] = connectorId */
};
static const ProtobufCIntRange start_transaction_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor start_transaction_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "startTransactionReq",
  "StartTransactionReq",
  "StartTransactionReq",
  "",
  sizeof(StartTransactionReq),
  3,
  start_transaction_req__field_descriptors,
  start_transaction_req__field_indices_by_name,
  1,  start_transaction_req__number_ranges,
  (ProtobufCMessageInit) start_transaction_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue start_transaction_resp__start_transaction_status_enum_type__enum_values_by_number[2] =
{
  { "Accepted", "START_TRANSACTION_RESP__START_TRANSACTION_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Rejected", "START_TRANSACTION_RESP__START_TRANSACTION_STATUS_ENUM_TYPE__Rejected", 1 },
};
static const ProtobufCIntRange start_transaction_resp__start_transaction_status_enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex start_transaction_resp__start_transaction_status_enum_type__enum_values_by_name[2] =
{
  { "Accepted", 0 },
  { "Rejected", 1 },
};
const ProtobufCEnumDescriptor start_transaction_resp__start_transaction_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "startTransactionResp.startTransactionStatusEnumType",
  "startTransactionStatusEnumType",
  "StartTransactionResp__StartTransactionStatusEnumType",
  "",
  2,
  start_transaction_resp__start_transaction_status_enum_type__enum_values_by_number,
  2,
  start_transaction_resp__start_transaction_status_enum_type__enum_values_by_name,
  1,
  start_transaction_resp__start_transaction_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue start_transaction_resp__start_transaction_error_enum_type__enum_values_by_number[5] =
{
  { "ConnectorUnavailable", "START_TRANSACTION_RESP__START_TRANSACTION_ERROR_ENUM_TYPE__ConnectorUnavailable", 0 },
  { "ConnectorFault", "START_TRANSACTION_RESP__START_TRANSACTION_ERROR_ENUM_TYPE__ConnectorFault", 2 },
  { "ConnectorInUse", "START_TRANSACTION_RESP__START_TRANSACTION_ERROR_ENUM_TYPE__ConnectorInUse", 3 },
  { "EVSEUnavailable", "START_TRANSACTION_RESP__START_TRANSACTION_ERROR_ENUM_TYPE__EVSEUnavailable", 4 },
  { "EVSEFault", "START_TRANSACTION_RESP__START_TRANSACTION_ERROR_ENUM_TYPE__EVSEFault", 5 },
};
static const ProtobufCIntRange start_transaction_resp__start_transaction_error_enum_type__value_ranges[] = {
{0, 0},{2, 1},{0, 5}
};
static const ProtobufCEnumValueIndex start_transaction_resp__start_transaction_error_enum_type__enum_values_by_name[5] =
{
  { "ConnectorFault", 1 },
  { "ConnectorInUse", 2 },
  { "ConnectorUnavailable", 0 },
  { "EVSEFault", 4 },
  { "EVSEUnavailable", 3 },
};
const ProtobufCEnumDescriptor start_transaction_resp__start_transaction_error_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "startTransactionResp.startTransactionErrorEnumType",
  "startTransactionErrorEnumType",
  "StartTransactionResp__StartTransactionErrorEnumType",
  "",
  5,
  start_transaction_resp__start_transaction_error_enum_type__enum_values_by_number,
  5,
  start_transaction_resp__start_transaction_error_enum_type__enum_values_by_name,
  2,
  start_transaction_resp__start_transaction_error_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor start_transaction_resp__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StartTransactionResp, status),
    &start_transaction_resp__start_transaction_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorCode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(StartTransactionResp, has_errorcode),
    offsetof(StartTransactionResp, errorcode),
    &start_transaction_resp__start_transaction_error_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned start_transaction_resp__field_indices_by_name[] = {
  1,   /* field[1] = errorCode */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange start_transaction_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor start_transaction_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "startTransactionResp",
  "StartTransactionResp",
  "StartTransactionResp",
  "",
  sizeof(StartTransactionResp),
  2,
  start_transaction_resp__field_descriptors,
  start_transaction_resp__field_indices_by_name,
  1,  start_transaction_resp__number_ranges,
  (ProtobufCMessageInit) start_transaction_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
