/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: statusNotification.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "statusNotification.pb-c.h"
void   status_notification_req__connectors_status_type__init
                     (StatusNotificationReq__ConnectorsStatusType         *message)
{
  static const StatusNotificationReq__ConnectorsStatusType init_value = STATUS_NOTIFICATION_REQ__CONNECTORS_STATUS_TYPE__INIT;
  *message = init_value;
}
void   status_notification_req__init
                     (StatusNotificationReq         *message)
{
  static const StatusNotificationReq init_value = STATUS_NOTIFICATION_REQ__INIT;
  *message = init_value;
}
size_t status_notification_req__get_packed_size
                     (const StatusNotificationReq *message)
{
  assert(message->base.descriptor == &status_notification_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_notification_req__pack
                     (const StatusNotificationReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_notification_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_notification_req__pack_to_buffer
                     (const StatusNotificationReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_notification_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusNotificationReq *
       status_notification_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusNotificationReq *)
     protobuf_c_message_unpack (&status_notification_req__descriptor,
                                allocator, len, data);
}
void   status_notification_req__free_unpacked
                     (StatusNotificationReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_notification_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   status_notification_resp__init
                     (StatusNotificationResp         *message)
{
  static const StatusNotificationResp init_value = STATUS_NOTIFICATION_RESP__INIT;
  *message = init_value;
}
size_t status_notification_resp__get_packed_size
                     (const StatusNotificationResp *message)
{
  assert(message->base.descriptor == &status_notification_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_notification_resp__pack
                     (const StatusNotificationResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_notification_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_notification_resp__pack_to_buffer
                     (const StatusNotificationResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_notification_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusNotificationResp *
       status_notification_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusNotificationResp *)
     protobuf_c_message_unpack (&status_notification_resp__descriptor,
                                allocator, len, data);
}
void   status_notification_resp__free_unpacked
                     (StatusNotificationResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_notification_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor status_notification_req__connectors_status_type__field_descriptors[3] =
{
  {
    "connectorId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatusNotificationReq__ConnectorsStatusType, connectorid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectorStatus",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StatusNotificationReq__ConnectorsStatusType, connectorstatus),
    &status_notification_req__connector_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "faultCode",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(StatusNotificationReq__ConnectorsStatusType, has_faultcode),
    offsetof(StatusNotificationReq__ConnectorsStatusType, faultcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_notification_req__connectors_status_type__field_indices_by_name[] = {
  0,   /* field[0] = connectorId */
  1,   /* field[1] = connectorStatus */
  2,   /* field[2] = faultCode */
};
static const ProtobufCIntRange status_notification_req__connectors_status_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor status_notification_req__connectors_status_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "statusNotificationReq.connectorsStatusType",
  "ConnectorsStatusType",
  "StatusNotificationReq__ConnectorsStatusType",
  "",
  sizeof(StatusNotificationReq__ConnectorsStatusType),
  3,
  status_notification_req__connectors_status_type__field_descriptors,
  status_notification_req__connectors_status_type__field_indices_by_name,
  1,  status_notification_req__connectors_status_type__number_ranges,
  (ProtobufCMessageInit) status_notification_req__connectors_status_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue status_notification_req__connector_status_enum_type__enum_values_by_number[5] =
{
  { "Available", "STATUS_NOTIFICATION_REQ__CONNECTOR_STATUS_ENUM_TYPE__Available", 0 },
  { "Occupied", "STATUS_NOTIFICATION_REQ__CONNECTOR_STATUS_ENUM_TYPE__Occupied", 1 },
  { "Reserved", "STATUS_NOTIFICATION_REQ__CONNECTOR_STATUS_ENUM_TYPE__Reserved", 2 },
  { "Unavailable", "STATUS_NOTIFICATION_REQ__CONNECTOR_STATUS_ENUM_TYPE__Unavailable", 3 },
  { "Faulted", "STATUS_NOTIFICATION_REQ__CONNECTOR_STATUS_ENUM_TYPE__Faulted", 4 },
};
static const ProtobufCIntRange status_notification_req__connector_status_enum_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex status_notification_req__connector_status_enum_type__enum_values_by_name[5] =
{
  { "Available", 0 },
  { "Faulted", 4 },
  { "Occupied", 1 },
  { "Reserved", 2 },
  { "Unavailable", 3 },
};
const ProtobufCEnumDescriptor status_notification_req__connector_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "statusNotificationReq.connectorStatusEnumType",
  "connectorStatusEnumType",
  "StatusNotificationReq__ConnectorStatusEnumType",
  "",
  5,
  status_notification_req__connector_status_enum_type__enum_values_by_number,
  5,
  status_notification_req__connector_status_enum_type__enum_values_by_name,
  1,
  status_notification_req__connector_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor status_notification_req__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(StatusNotificationReq, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectorsStatus",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StatusNotificationReq, n_connectorsstatus),
    offsetof(StatusNotificationReq, connectorsstatus),
    &status_notification_req__connectors_status_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_notification_req__field_indices_by_name[] = {
  1,   /* field[1] = connectorsStatus */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange status_notification_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor status_notification_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "statusNotificationReq",
  "StatusNotificationReq",
  "StatusNotificationReq",
  "",
  sizeof(StatusNotificationReq),
  2,
  status_notification_req__field_descriptors,
  status_notification_req__field_indices_by_name,
  1,  status_notification_req__number_ranges,
  (ProtobufCMessageInit) status_notification_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define status_notification_resp__field_descriptors NULL
#define status_notification_resp__field_indices_by_name NULL
#define status_notification_resp__number_ranges NULL
const ProtobufCMessageDescriptor status_notification_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "statusNotificationResp",
  "StatusNotificationResp",
  "StatusNotificationResp",
  "",
  sizeof(StatusNotificationResp),
  0,
  status_notification_resp__field_descriptors,
  status_notification_resp__field_indices_by_name,
  0,  status_notification_resp__number_ranges,
  (ProtobufCMessageInit) status_notification_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
