/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stopTransaction.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stopTransaction.pb-c.h"
void   stop_transaction_req__init
                     (StopTransactionReq         *message)
{
  static const StopTransactionReq init_value = STOP_TRANSACTION_REQ__INIT;
  *message = init_value;
}
size_t stop_transaction_req__get_packed_size
                     (const StopTransactionReq *message)
{
  assert(message->base.descriptor == &stop_transaction_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stop_transaction_req__pack
                     (const StopTransactionReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stop_transaction_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stop_transaction_req__pack_to_buffer
                     (const StopTransactionReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stop_transaction_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopTransactionReq *
       stop_transaction_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopTransactionReq *)
     protobuf_c_message_unpack (&stop_transaction_req__descriptor,
                                allocator, len, data);
}
void   stop_transaction_req__free_unpacked
                     (StopTransactionReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stop_transaction_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stop_transaction_resp__init
                     (StopTransactionResp         *message)
{
  static const StopTransactionResp init_value = STOP_TRANSACTION_RESP__INIT;
  *message = init_value;
}
size_t stop_transaction_resp__get_packed_size
                     (const StopTransactionResp *message)
{
  assert(message->base.descriptor == &stop_transaction_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stop_transaction_resp__pack
                     (const StopTransactionResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stop_transaction_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stop_transaction_resp__pack_to_buffer
                     (const StopTransactionResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stop_transaction_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StopTransactionResp *
       stop_transaction_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StopTransactionResp *)
     protobuf_c_message_unpack (&stop_transaction_resp__descriptor,
                                allocator, len, data);
}
void   stop_transaction_resp__free_unpacked
                     (StopTransactionResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stop_transaction_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stop_transaction_req__field_descriptors[1] =
{
  {
    "transactionID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(StopTransactionReq, transactionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_transaction_req__field_indices_by_name[] = {
  0,   /* field[0] = transactionID */
};
static const ProtobufCIntRange stop_transaction_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor stop_transaction_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "stopTransactionReq",
  "StopTransactionReq",
  "StopTransactionReq",
  "",
  sizeof(StopTransactionReq),
  1,
  stop_transaction_req__field_descriptors,
  stop_transaction_req__field_indices_by_name,
  1,  stop_transaction_req__number_ranges,
  (ProtobufCMessageInit) stop_transaction_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue stop_transaction_resp__error_code_enum_type__enum_values_by_number[1] =
{
  { "TransactionIDNotFound", "STOP_TRANSACTION_RESP__ERROR_CODE_ENUM_TYPE__TransactionIDNotFound", 0 },
};
static const ProtobufCIntRange stop_transaction_resp__error_code_enum_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex stop_transaction_resp__error_code_enum_type__enum_values_by_name[1] =
{
  { "TransactionIDNotFound", 0 },
};
const ProtobufCEnumDescriptor stop_transaction_resp__error_code_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "stopTransactionResp.errorCodeEnumType",
  "errorCodeEnumType",
  "StopTransactionResp__ErrorCodeEnumType",
  "",
  1,
  stop_transaction_resp__error_code_enum_type__enum_values_by_number,
  1,
  stop_transaction_resp__error_code_enum_type__enum_values_by_name,
  1,
  stop_transaction_resp__error_code_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue stop_transaction_resp__stop_status_enum_type__enum_values_by_number[2] =
{
  { "Accepted", "STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Rejected", "STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE__Rejected", 1 },
};
static const ProtobufCIntRange stop_transaction_resp__stop_status_enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex stop_transaction_resp__stop_status_enum_type__enum_values_by_name[2] =
{
  { "Accepted", 0 },
  { "Rejected", 1 },
};
const ProtobufCEnumDescriptor stop_transaction_resp__stop_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "stopTransactionResp.stopStatusEnumType",
  "stopStatusEnumType",
  "StopTransactionResp__StopStatusEnumType",
  "",
  2,
  stop_transaction_resp__stop_status_enum_type__enum_values_by_number,
  2,
  stop_transaction_resp__stop_status_enum_type__enum_values_by_name,
  1,
  stop_transaction_resp__stop_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor stop_transaction_resp__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StopTransactionResp, status),
    &stop_transaction_resp__stop_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorCode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(StopTransactionResp, has_errorcode),
    offsetof(StopTransactionResp, errorcode),
    &stop_transaction_resp__error_code_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stop_transaction_resp__field_indices_by_name[] = {
  1,   /* field[1] = errorCode */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange stop_transaction_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stop_transaction_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "stopTransactionResp",
  "StopTransactionResp",
  "StopTransactionResp",
  "",
  sizeof(StopTransactionResp),
  2,
  stop_transaction_resp__field_descriptors,
  stop_transaction_resp__field_indices_by_name,
  1,  stop_transaction_resp__number_ranges,
  (ProtobufCMessageInit) stop_transaction_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
