/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stopTransaction.proto */

#ifndef PROTOBUF_C_stopTransaction_2eproto__INCLUDED
#define PROTOBUF_C_stopTransaction_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _StopTransactionReq StopTransactionReq;
typedef struct _StopTransactionResp StopTransactionResp;


/* --- enums --- */

typedef enum _StopTransactionResp__ErrorCodeEnumType {
  STOP_TRANSACTION_RESP__ERROR_CODE_ENUM_TYPE__TransactionIDNotFound = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STOP_TRANSACTION_RESP__ERROR_CODE_ENUM_TYPE)
} StopTransactionResp__ErrorCodeEnumType;
typedef enum _StopTransactionResp__StopStatusEnumType {
  STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE__Accepted = 0,
  STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE__Rejected = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE)
} StopTransactionResp__StopStatusEnumType;

/* --- messages --- */

struct  _StopTransactionReq
{
  ProtobufCMessage base;
  ProtobufCBinaryData transactionid;
};
#define STOP_TRANSACTION_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stop_transaction_req__descriptor) \
    , {0,NULL} }


struct  _StopTransactionResp
{
  ProtobufCMessage base;
  StopTransactionResp__StopStatusEnumType status;
  protobuf_c_boolean has_errorcode;
  StopTransactionResp__ErrorCodeEnumType errorcode;
};
#define STOP_TRANSACTION_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stop_transaction_resp__descriptor) \
    , STOP_TRANSACTION_RESP__STOP_STATUS_ENUM_TYPE__Accepted, 0, STOP_TRANSACTION_RESP__ERROR_CODE_ENUM_TYPE__TransactionIDNotFound }


/* StopTransactionReq methods */
void   stop_transaction_req__init
                     (StopTransactionReq         *message);
size_t stop_transaction_req__get_packed_size
                     (const StopTransactionReq   *message);
size_t stop_transaction_req__pack
                     (const StopTransactionReq   *message,
                      uint8_t             *out);
size_t stop_transaction_req__pack_to_buffer
                     (const StopTransactionReq   *message,
                      ProtobufCBuffer     *buffer);
StopTransactionReq *
       stop_transaction_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stop_transaction_req__free_unpacked
                     (StopTransactionReq *message,
                      ProtobufCAllocator *allocator);
/* StopTransactionResp methods */
void   stop_transaction_resp__init
                     (StopTransactionResp         *message);
size_t stop_transaction_resp__get_packed_size
                     (const StopTransactionResp   *message);
size_t stop_transaction_resp__pack
                     (const StopTransactionResp   *message,
                      uint8_t             *out);
size_t stop_transaction_resp__pack_to_buffer
                     (const StopTransactionResp   *message,
                      ProtobufCBuffer     *buffer);
StopTransactionResp *
       stop_transaction_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stop_transaction_resp__free_unpacked
                     (StopTransactionResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StopTransactionReq_Closure)
                 (const StopTransactionReq *message,
                  void *closure_data);
typedef void (*StopTransactionResp_Closure)
                 (const StopTransactionResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor stop_transaction_req__descriptor;
extern const ProtobufCMessageDescriptor stop_transaction_resp__descriptor;
extern const ProtobufCEnumDescriptor    stop_transaction_resp__error_code_enum_type__descriptor;
extern const ProtobufCEnumDescriptor    stop_transaction_resp__stop_status_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_stopTransaction_2eproto__INCLUDED */
