/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: transactionEvent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "transactionEvent.pb-c.h"
void   transaction_event_req__transaction_type__init
                     (TransactionEventReq__TransactionType         *message)
{
  static const TransactionEventReq__TransactionType init_value = TRANSACTION_EVENT_REQ__TRANSACTION_TYPE__INIT;
  *message = init_value;
}
void   transaction_event_req__init
                     (TransactionEventReq         *message)
{
  static const TransactionEventReq init_value = TRANSACTION_EVENT_REQ__INIT;
  *message = init_value;
}
size_t transaction_event_req__get_packed_size
                     (const TransactionEventReq *message)
{
  assert(message->base.descriptor == &transaction_event_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transaction_event_req__pack
                     (const TransactionEventReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &transaction_event_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transaction_event_req__pack_to_buffer
                     (const TransactionEventReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &transaction_event_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransactionEventReq *
       transaction_event_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransactionEventReq *)
     protobuf_c_message_unpack (&transaction_event_req__descriptor,
                                allocator, len, data);
}
void   transaction_event_req__free_unpacked
                     (TransactionEventReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &transaction_event_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transaction_event_resp__init
                     (TransactionEventResp         *message)
{
  static const TransactionEventResp init_value = TRANSACTION_EVENT_RESP__INIT;
  *message = init_value;
}
size_t transaction_event_resp__get_packed_size
                     (const TransactionEventResp *message)
{
  assert(message->base.descriptor == &transaction_event_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transaction_event_resp__pack
                     (const TransactionEventResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &transaction_event_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transaction_event_resp__pack_to_buffer
                     (const TransactionEventResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &transaction_event_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransactionEventResp *
       transaction_event_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransactionEventResp *)
     protobuf_c_message_unpack (&transaction_event_resp__descriptor,
                                allocator, len, data);
}
void   transaction_event_resp__free_unpacked
                     (TransactionEventResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &transaction_event_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor transaction_event_req__transaction_type__field_descriptors[4] =
{
  {
    "chargingState",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TransactionEventReq__TransactionType, has_chargingstate),
    offsetof(TransactionEventReq__TransactionType, chargingstate),
    &transaction_event_req__charging_state_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeSpentCharging",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionEventReq__TransactionType, has_timespentcharging),
    offsetof(TransactionEventReq__TransactionType, timespentcharging),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stoppedReason",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TransactionEventReq__TransactionType, has_stoppedreason),
    offsetof(TransactionEventReq__TransactionType, stoppedreason),
    &transaction_event_req__reason_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionID",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TransactionEventReq__TransactionType, has_transactionid),
    offsetof(TransactionEventReq__TransactionType, transactionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transaction_event_req__transaction_type__field_indices_by_name[] = {
  0,   /* field[0] = chargingState */
  2,   /* field[2] = stoppedReason */
  1,   /* field[1] = timeSpentCharging */
  3,   /* field[3] = transactionID */
};
static const ProtobufCIntRange transaction_event_req__transaction_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor transaction_event_req__transaction_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "transactionEventReq.transactionType",
  "TransactionType",
  "TransactionEventReq__TransactionType",
  "",
  sizeof(TransactionEventReq__TransactionType),
  4,
  transaction_event_req__transaction_type__field_descriptors,
  transaction_event_req__transaction_type__field_indices_by_name,
  1,  transaction_event_req__transaction_type__number_ranges,
  (ProtobufCMessageInit) transaction_event_req__transaction_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue transaction_event_req__transaction_event_enum_type__enum_values_by_number[3] =
{
  { "Ended", "TRANSACTION_EVENT_REQ__TRANSACTION_EVENT_ENUM_TYPE__Ended", 0 },
  { "Started", "TRANSACTION_EVENT_REQ__TRANSACTION_EVENT_ENUM_TYPE__Started", 1 },
  { "Updated", "TRANSACTION_EVENT_REQ__TRANSACTION_EVENT_ENUM_TYPE__Updated", 2 },
};
static const ProtobufCIntRange transaction_event_req__transaction_event_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex transaction_event_req__transaction_event_enum_type__enum_values_by_name[3] =
{
  { "Ended", 0 },
  { "Started", 1 },
  { "Updated", 2 },
};
const ProtobufCEnumDescriptor transaction_event_req__transaction_event_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "transactionEventReq.transactionEventEnumType",
  "transactionEventEnumType",
  "TransactionEventReq__TransactionEventEnumType",
  "",
  3,
  transaction_event_req__transaction_event_enum_type__enum_values_by_number,
  3,
  transaction_event_req__transaction_event_enum_type__enum_values_by_name,
  1,
  transaction_event_req__transaction_event_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue transaction_event_req__charging_state_enum_type__enum_values_by_number[2] =
{
  { "Charging", "TRANSACTION_EVENT_REQ__CHARGING_STATE_ENUM_TYPE__Charging", 0 },
  { "Suspended", "TRANSACTION_EVENT_REQ__CHARGING_STATE_ENUM_TYPE__Suspended", 1 },
};
static const ProtobufCIntRange transaction_event_req__charging_state_enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex transaction_event_req__charging_state_enum_type__enum_values_by_name[2] =
{
  { "Charging", 0 },
  { "Suspended", 1 },
};
const ProtobufCEnumDescriptor transaction_event_req__charging_state_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "transactionEventReq.chargingStateEnumType",
  "chargingStateEnumType",
  "TransactionEventReq__ChargingStateEnumType",
  "",
  2,
  transaction_event_req__charging_state_enum_type__enum_values_by_number,
  2,
  transaction_event_req__charging_state_enum_type__enum_values_by_name,
  1,
  transaction_event_req__charging_state_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue transaction_event_req__reason_enum_type__enum_values_by_number[13] =
{
  { "DeAuthorized", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__DeAuthorized", 0 },
  { "Local", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__Local", 1 },
  { "EnergyLimitReached", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__EnergyLimitReached", 2 },
  { "EVDisconnected", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__EVDisconnected", 3 },
  { "GroundFault", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__GroundFault", 4 },
  { "OvercurrrendFault", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__OvercurrrendFault", 5 },
  { "PowerLoss", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__PowerLoss", 6 },
  { "PowerQuality", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__PowerQuality", 7 },
  { "Remote", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__Remote", 8 },
  { "TimeLimitReached", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__TimeLimitReached", 9 },
  { "Timeout", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__Timeout", 10 },
  { "SOCLimitReached", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__SOCLimitReached", 11 },
  { "ImmediateReset", "TRANSACTION_EVENT_REQ__REASON_ENUM_TYPE__ImmediateReset", 12 },
};
static const ProtobufCIntRange transaction_event_req__reason_enum_type__value_ranges[] = {
{0, 0},{0, 13}
};
static const ProtobufCEnumValueIndex transaction_event_req__reason_enum_type__enum_values_by_name[13] =
{
  { "DeAuthorized", 0 },
  { "EVDisconnected", 3 },
  { "EnergyLimitReached", 2 },
  { "GroundFault", 4 },
  { "ImmediateReset", 12 },
  { "Local", 1 },
  { "OvercurrrendFault", 5 },
  { "PowerLoss", 6 },
  { "PowerQuality", 7 },
  { "Remote", 8 },
  { "SOCLimitReached", 11 },
  { "TimeLimitReached", 9 },
  { "Timeout", 10 },
};
const ProtobufCEnumDescriptor transaction_event_req__reason_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "transactionEventReq.reasonEnumType",
  "reasonEnumType",
  "TransactionEventReq__ReasonEnumType",
  "",
  13,
  transaction_event_req__reason_enum_type__enum_values_by_number,
  13,
  transaction_event_req__reason_enum_type__enum_values_by_name,
  1,
  transaction_event_req__reason_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor transaction_event_req__field_descriptors[7] =
{
  {
    "eventType",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TransactionEventReq, eventtype),
    &transaction_event_req__transaction_event_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TransactionEventReq, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transaction",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TransactionEventReq, transaction),
    &transaction_event_req__transaction_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IDToken",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TransactionEventReq, idtoken),
    &idtoken_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectorId",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionEventReq, has_connectorid),
    offsetof(TransactionEventReq, connectorid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalTime",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionEventReq, has_totaltime),
    offsetof(TransactionEventReq, totaltime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalCost",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionEventReq, has_totalcost),
    offsetof(TransactionEventReq, totalcost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transaction_event_req__field_indices_by_name[] = {
  3,   /* field[3] = IDToken */
  4,   /* field[4] = connectorId */
  0,   /* field[0] = eventType */
  1,   /* field[1] = timestamp */
  6,   /* field[6] = totalCost */
  5,   /* field[5] = totalTime */
  2,   /* field[2] = transaction */
};
static const ProtobufCIntRange transaction_event_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor transaction_event_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "transactionEventReq",
  "TransactionEventReq",
  "TransactionEventReq",
  "",
  sizeof(TransactionEventReq),
  7,
  transaction_event_req__field_descriptors,
  transaction_event_req__field_indices_by_name,
  1,  transaction_event_req__number_ranges,
  (ProtobufCMessageInit) transaction_event_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue transaction_event_resp__transaction_status_enum_type__enum_values_by_number[3] =
{
  { "Accepted", "TRANSACTION_EVENT_RESP__TRANSACTION_STATUS_ENUM_TYPE__Accepted", 0 },
  { "TranssctionProcing", "TRANSACTION_EVENT_RESP__TRANSACTION_STATUS_ENUM_TYPE__TranssctionProcing", 1 },
  { "TransactionIdExist", "TRANSACTION_EVENT_RESP__TRANSACTION_STATUS_ENUM_TYPE__TransactionIdExist", 2 },
};
static const ProtobufCIntRange transaction_event_resp__transaction_status_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex transaction_event_resp__transaction_status_enum_type__enum_values_by_name[3] =
{
  { "Accepted", 0 },
  { "TransactionIdExist", 2 },
  { "TranssctionProcing", 1 },
};
const ProtobufCEnumDescriptor transaction_event_resp__transaction_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "transactionEventResp.transactionStatusEnumType",
  "transactionStatusEnumType",
  "TransactionEventResp__TransactionStatusEnumType",
  "",
  3,
  transaction_event_resp__transaction_status_enum_type__enum_values_by_number,
  3,
  transaction_event_resp__transaction_status_enum_type__enum_values_by_name,
  1,
  transaction_event_resp__transaction_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor transaction_event_resp__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TransactionEventResp, status),
    &transaction_event_resp__transaction_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactionID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TransactionEventResp, transactionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transaction_event_resp__field_indices_by_name[] = {
  0,   /* field[0] = status */
  1,   /* field[1] = transactionID */
};
static const ProtobufCIntRange transaction_event_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor transaction_event_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "transactionEventResp",
  "TransactionEventResp",
  "TransactionEventResp",
  "",
  sizeof(TransactionEventResp),
  2,
  transaction_event_resp__field_descriptors,
  transaction_event_resp__field_indices_by_name,
  1,  transaction_event_resp__number_ranges,
  (ProtobufCMessageInit) transaction_event_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
