/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: updateFirmwareEvent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "updateFirmwareEvent.pb-c.h"
void   update_firmware_event_req__update_by_ftpdata__init
                     (UpdateFirmwareEventReq__UpdateByFTPData         *message)
{
  static const UpdateFirmwareEventReq__UpdateByFTPData init_value = UPDATE_FIRMWARE_EVENT_REQ__UPDATE_BY_FTPDATA__INIT;
  *message = init_value;
}
void   update_firmware_event_req__update_param_type__init
                     (UpdateFirmwareEventReq__UpdateParamType         *message)
{
  static const UpdateFirmwareEventReq__UpdateParamType init_value = UPDATE_FIRMWARE_EVENT_REQ__UPDATE_PARAM_TYPE__INIT;
  *message = init_value;
}
void   update_firmware_event_req__init
                     (UpdateFirmwareEventReq         *message)
{
  static const UpdateFirmwareEventReq init_value = UPDATE_FIRMWARE_EVENT_REQ__INIT;
  *message = init_value;
}
size_t update_firmware_event_req__get_packed_size
                     (const UpdateFirmwareEventReq *message)
{
  assert(message->base.descriptor == &update_firmware_event_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_firmware_event_req__pack
                     (const UpdateFirmwareEventReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_firmware_event_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_firmware_event_req__pack_to_buffer
                     (const UpdateFirmwareEventReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_firmware_event_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateFirmwareEventReq *
       update_firmware_event_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateFirmwareEventReq *)
     protobuf_c_message_unpack (&update_firmware_event_req__descriptor,
                                allocator, len, data);
}
void   update_firmware_event_req__free_unpacked
                     (UpdateFirmwareEventReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_firmware_event_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_firmware_event_resp__init
                     (UpdateFirmwareEventResp         *message)
{
  static const UpdateFirmwareEventResp init_value = UPDATE_FIRMWARE_EVENT_RESP__INIT;
  *message = init_value;
}
size_t update_firmware_event_resp__get_packed_size
                     (const UpdateFirmwareEventResp *message)
{
  assert(message->base.descriptor == &update_firmware_event_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_firmware_event_resp__pack
                     (const UpdateFirmwareEventResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_firmware_event_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_firmware_event_resp__pack_to_buffer
                     (const UpdateFirmwareEventResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_firmware_event_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateFirmwareEventResp *
       update_firmware_event_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateFirmwareEventResp *)
     protobuf_c_message_unpack (&update_firmware_event_resp__descriptor,
                                allocator, len, data);
}
void   update_firmware_event_resp__free_unpacked
                     (UpdateFirmwareEventResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_firmware_event_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const int32_t update_firmware_event_req__update_by_ftpdata__retries__default_value = 3;
static const ProtobufCFieldDescriptor update_firmware_event_req__update_by_ftpdata__field_descriptors[2] =
{
  {
    "location",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventReq__UpdateByFTPData, location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retries",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(UpdateFirmwareEventReq__UpdateByFTPData, has_retries),
    offsetof(UpdateFirmwareEventReq__UpdateByFTPData, retries),
    NULL,
    &update_firmware_event_req__update_by_ftpdata__retries__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_firmware_event_req__update_by_ftpdata__field_indices_by_name[] = {
  0,   /* field[0] = location */
  1,   /* field[1] = retries */
};
static const ProtobufCIntRange update_firmware_event_req__update_by_ftpdata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor update_firmware_event_req__update_by_ftpdata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "updateFirmwareEventReq.updateByFTPData",
  "UpdateByFTPData",
  "UpdateFirmwareEventReq__UpdateByFTPData",
  "",
  sizeof(UpdateFirmwareEventReq__UpdateByFTPData),
  2,
  update_firmware_event_req__update_by_ftpdata__field_descriptors,
  update_firmware_event_req__update_by_ftpdata__field_indices_by_name,
  1,  update_firmware_event_req__update_by_ftpdata__number_ranges,
  (ProtobufCMessageInit) update_firmware_event_req__update_by_ftpdata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor update_firmware_event_req__update_param_type__field_descriptors[4] =
{
  {
    "updateMethod",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventReq__UpdateParamType, updatemethod),
    &update_firmware_event_req__update_method_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventReq__UpdateParamType, location),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retries",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(UpdateFirmwareEventReq__UpdateParamType, has_retries),
    offsetof(UpdateFirmwareEventReq__UpdateParamType, retries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxPackageSize",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(UpdateFirmwareEventReq__UpdateParamType, has_maxpackagesize),
    offsetof(UpdateFirmwareEventReq__UpdateParamType, maxpackagesize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_firmware_event_req__update_param_type__field_indices_by_name[] = {
  1,   /* field[1] = location */
  3,   /* field[3] = maxPackageSize */
  2,   /* field[2] = retries */
  0,   /* field[0] = updateMethod */
};
static const ProtobufCIntRange update_firmware_event_req__update_param_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor update_firmware_event_req__update_param_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "updateFirmwareEventReq.updateParamType",
  "UpdateParamType",
  "UpdateFirmwareEventReq__UpdateParamType",
  "",
  sizeof(UpdateFirmwareEventReq__UpdateParamType),
  4,
  update_firmware_event_req__update_param_type__field_descriptors,
  update_firmware_event_req__update_param_type__field_indices_by_name,
  1,  update_firmware_event_req__update_param_type__number_ranges,
  (ProtobufCMessageInit) update_firmware_event_req__update_param_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue update_firmware_event_req__update_event_type_enum_type__enum_values_by_number[3] =
{
  { "Started", "UPDATE_FIRMWARE_EVENT_REQ__UPDATE_EVENT_TYPE_ENUM_TYPE__Started", 0 },
  { "Canceled", "UPDATE_FIRMWARE_EVENT_REQ__UPDATE_EVENT_TYPE_ENUM_TYPE__Canceled", 1 },
  { "Paused", "UPDATE_FIRMWARE_EVENT_REQ__UPDATE_EVENT_TYPE_ENUM_TYPE__Paused", 2 },
};
static const ProtobufCIntRange update_firmware_event_req__update_event_type_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex update_firmware_event_req__update_event_type_enum_type__enum_values_by_name[3] =
{
  { "Canceled", 1 },
  { "Paused", 2 },
  { "Started", 0 },
};
const ProtobufCEnumDescriptor update_firmware_event_req__update_event_type_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "updateFirmwareEventReq.updateEventTypeEnumType",
  "updateEventTypeEnumType",
  "UpdateFirmwareEventReq__UpdateEventTypeEnumType",
  "",
  3,
  update_firmware_event_req__update_event_type_enum_type__enum_values_by_number,
  3,
  update_firmware_event_req__update_event_type_enum_type__enum_values_by_name,
  1,
  update_firmware_event_req__update_event_type_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue update_firmware_event_req__update_method_enum_type__enum_values_by_number[2] =
{
  { "UpdateByCSMS", "UPDATE_FIRMWARE_EVENT_REQ__UPDATE_METHOD_ENUM_TYPE__UpdateByCSMS", 0 },
  { "UpdateByFTP", "UPDATE_FIRMWARE_EVENT_REQ__UPDATE_METHOD_ENUM_TYPE__UpdateByFTP", 1 },
};
static const ProtobufCIntRange update_firmware_event_req__update_method_enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_firmware_event_req__update_method_enum_type__enum_values_by_name[2] =
{
  { "UpdateByCSMS", 0 },
  { "UpdateByFTP", 1 },
};
const ProtobufCEnumDescriptor update_firmware_event_req__update_method_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "updateFirmwareEventReq.updateMethodEnumType",
  "updateMethodEnumType",
  "UpdateFirmwareEventReq__UpdateMethodEnumType",
  "",
  2,
  update_firmware_event_req__update_method_enum_type__enum_values_by_number,
  2,
  update_firmware_event_req__update_method_enum_type__enum_values_by_name,
  1,
  update_firmware_event_req__update_method_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor update_firmware_event_req__field_descriptors[2] =
{
  {
    "eventType",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventReq, eventtype),
    &update_firmware_event_req__update_event_type_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "updateParam",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventReq, updateparam),
    &update_firmware_event_req__update_param_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_firmware_event_req__field_indices_by_name[] = {
  0,   /* field[0] = eventType */
  1,   /* field[1] = updateParam */
};
static const ProtobufCIntRange update_firmware_event_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor update_firmware_event_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "updateFirmwareEventReq",
  "UpdateFirmwareEventReq",
  "UpdateFirmwareEventReq",
  "",
  sizeof(UpdateFirmwareEventReq),
  2,
  update_firmware_event_req__field_descriptors,
  update_firmware_event_req__field_indices_by_name,
  1,  update_firmware_event_req__number_ranges,
  (ProtobufCMessageInit) update_firmware_event_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue update_firmware_event_resp__update_firmware_status_enum_type__enum_values_by_number[3] =
{
  { "Accepted", "UPDATE_FIRMWARE_EVENT_RESP__UPDATE_FIRMWARE_STATUS_ENUM_TYPE__Accepted", 0 },
  { "Rejected", "UPDATE_FIRMWARE_EVENT_RESP__UPDATE_FIRMWARE_STATUS_ENUM_TYPE__Rejected", 1 },
  { "AcceptedCanceled", "UPDATE_FIRMWARE_EVENT_RESP__UPDATE_FIRMWARE_STATUS_ENUM_TYPE__AcceptedCanceled", 2 },
};
static const ProtobufCIntRange update_firmware_event_resp__update_firmware_status_enum_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex update_firmware_event_resp__update_firmware_status_enum_type__enum_values_by_name[3] =
{
  { "Accepted", 0 },
  { "AcceptedCanceled", 2 },
  { "Rejected", 1 },
};
const ProtobufCEnumDescriptor update_firmware_event_resp__update_firmware_status_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "updateFirmwareEventResp.updateFirmwareStatusEnumType",
  "updateFirmwareStatusEnumType",
  "UpdateFirmwareEventResp__UpdateFirmwareStatusEnumType",
  "",
  3,
  update_firmware_event_resp__update_firmware_status_enum_type__enum_values_by_number,
  3,
  update_firmware_event_resp__update_firmware_status_enum_type__enum_values_by_name,
  1,
  update_firmware_event_resp__update_firmware_status_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor update_firmware_event_resp__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateFirmwareEventResp, status),
    &update_firmware_event_resp__update_firmware_status_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_firmware_event_resp__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange update_firmware_event_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor update_firmware_event_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "updateFirmwareEventResp",
  "UpdateFirmwareEventResp",
  "UpdateFirmwareEventResp",
  "",
  sizeof(UpdateFirmwareEventResp),
  1,
  update_firmware_event_resp__field_descriptors,
  update_firmware_event_resp__field_indices_by_name,
  1,  update_firmware_event_resp__number_ranges,
  (ProtobufCMessageInit) update_firmware_event_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
