/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: variableType.proto */

#ifndef PROTOBUF_C_variableType_2eproto__INCLUDED
#define PROTOBUF_C_variableType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "variableCharacteristicsType.pb-c.h"

typedef struct _VariableType VariableType;


/* --- enums --- */


/* --- messages --- */

struct  _VariableType
{
  ProtobufCMessage base;
  char *name;
  char *instance;
  VariableCharacteristicsType *variablecharacteristics;
};
#define VARIABLE_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&variable_type__descriptor) \
    , NULL, NULL, NULL }


/* VariableType methods */
void   variable_type__init
                     (VariableType         *message);
size_t variable_type__get_packed_size
                     (const VariableType   *message);
size_t variable_type__pack
                     (const VariableType   *message,
                      uint8_t             *out);
size_t variable_type__pack_to_buffer
                     (const VariableType   *message,
                      ProtobufCBuffer     *buffer);
VariableType *
       variable_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   variable_type__free_unpacked
                     (VariableType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*VariableType_Closure)
                 (const VariableType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor variable_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_variableType_2eproto__INCLUDED */
