/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: variableCharacteristicsType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "variableCharacteristicsType.pb-c.h"
void   variable_characteristics_type__init
                     (VariableCharacteristicsType         *message)
{
  static const VariableCharacteristicsType init_value = VARIABLE_CHARACTERISTICS_TYPE__INIT;
  *message = init_value;
}
size_t variable_characteristics_type__get_packed_size
                     (const VariableCharacteristicsType *message)
{
  assert(message->base.descriptor == &variable_characteristics_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t variable_characteristics_type__pack
                     (const VariableCharacteristicsType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &variable_characteristics_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t variable_characteristics_type__pack_to_buffer
                     (const VariableCharacteristicsType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &variable_characteristics_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VariableCharacteristicsType *
       variable_characteristics_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VariableCharacteristicsType *)
     protobuf_c_message_unpack (&variable_characteristics_type__descriptor,
                                allocator, len, data);
}
void   variable_characteristics_type__free_unpacked
                     (VariableCharacteristicsType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &variable_characteristics_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue variable_characteristics_type__date_enum_type__enum_values_by_number[4] =
{
  { "String", "VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__String", 0 },
  { "Decimal", "VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__Decimal", 1 },
  { "Integer", "VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__Integer", 2 },
  { "DateTime", "VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__DateTime", 3 },
};
static const ProtobufCIntRange variable_characteristics_type__date_enum_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex variable_characteristics_type__date_enum_type__enum_values_by_name[4] =
{
  { "DateTime", 3 },
  { "Decimal", 1 },
  { "Integer", 2 },
  { "String", 0 },
};
const ProtobufCEnumDescriptor variable_characteristics_type__date_enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "variableCharacteristicsType.DateEnumType",
  "DateEnumType",
  "VariableCharacteristicsType__DateEnumType",
  "",
  4,
  variable_characteristics_type__date_enum_type__enum_values_by_number,
  4,
  variable_characteristics_type__date_enum_type__enum_values_by_name,
  1,
  variable_characteristics_type__date_enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor variable_characteristics_type__field_descriptors[6] =
{
  {
    "units",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VariableCharacteristicsType, units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataType",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(VariableCharacteristicsType, datatype),
    &variable_characteristics_type__date_enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minLimit",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(VariableCharacteristicsType, has_minlimit),
    offsetof(VariableCharacteristicsType, minlimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxLimit",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(VariableCharacteristicsType, has_maxlimit),
    offsetof(VariableCharacteristicsType, maxlimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valuesList",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(VariableCharacteristicsType, n_valueslist),
    offsetof(VariableCharacteristicsType, valueslist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supportsMonitoring",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(VariableCharacteristicsType, supportsmonitoring),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned variable_characteristics_type__field_indices_by_name[] = {
  1,   /* field[1] = dataType */
  3,   /* field[3] = maxLimit */
  2,   /* field[2] = minLimit */
  5,   /* field[5] = supportsMonitoring */
  0,   /* field[0] = units */
  4,   /* field[4] = valuesList */
};
static const ProtobufCIntRange variable_characteristics_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor variable_characteristics_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "variableCharacteristicsType",
  "VariableCharacteristicsType",
  "VariableCharacteristicsType",
  "",
  sizeof(VariableCharacteristicsType),
  6,
  variable_characteristics_type__field_descriptors,
  variable_characteristics_type__field_indices_by_name,
  1,  variable_characteristics_type__number_ranges,
  (ProtobufCMessageInit) variable_characteristics_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
