/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: variableType.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "variableType.pb-c.h"
void   variable_type__init
                     (VariableType         *message)
{
  static const VariableType init_value = VARIABLE_TYPE__INIT;
  *message = init_value;
}
size_t variable_type__get_packed_size
                     (const VariableType *message)
{
  assert(message->base.descriptor == &variable_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t variable_type__pack
                     (const VariableType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &variable_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t variable_type__pack_to_buffer
                     (const VariableType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &variable_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VariableType *
       variable_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VariableType *)
     protobuf_c_message_unpack (&variable_type__descriptor,
                                allocator, len, data);
}
void   variable_type__free_unpacked
                     (VariableType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &variable_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor variable_type__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VariableType, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VariableType, instance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "variableCharacteristics",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(VariableType, variablecharacteristics),
    &variable_characteristics_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned variable_type__field_indices_by_name[] = {
  1,   /* field[1] = instance */
  0,   /* field[0] = name */
  2,   /* field[2] = variableCharacteristics */
};
static const ProtobufCIntRange variable_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor variable_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "variableType",
  "VariableType",
  "VariableType",
  "",
  sizeof(VariableType),
  3,
  variable_type__field_descriptors,
  variable_type__field_indices_by_name,
  1,  variable_type__number_ranges,
  (ProtobufCMessageInit) variable_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
