/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: variableCharacteristicsType.proto */

#ifndef PROTOBUF_C_variableCharacteristicsType_2eproto__INCLUDED
#define PROTOBUF_C_variableCharacteristicsType_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _VariableCharacteristicsType VariableCharacteristicsType;


/* --- enums --- */

typedef enum _VariableCharacteristicsType__DateEnumType {
  VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__String = 0,
  VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__Decimal = 1,
  VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__Integer = 2,
  VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__DateTime = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE)
} VariableCharacteristicsType__DateEnumType;

/* --- messages --- */

struct  _VariableCharacteristicsType
{
  ProtobufCMessage base;
  char *units;
  VariableCharacteristicsType__DateEnumType datatype;
  protobuf_c_boolean has_minlimit;
  int32_t minlimit;
  protobuf_c_boolean has_maxlimit;
  int32_t maxlimit;
  size_t n_valueslist;
  char **valueslist;
  protobuf_c_boolean supportsmonitoring;
};
#define VARIABLE_CHARACTERISTICS_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&variable_characteristics_type__descriptor) \
    , NULL, VARIABLE_CHARACTERISTICS_TYPE__DATE_ENUM_TYPE__String, 0, 0, 0, 0, 0,NULL, 0 }


/* VariableCharacteristicsType methods */
void   variable_characteristics_type__init
                     (VariableCharacteristicsType         *message);
size_t variable_characteristics_type__get_packed_size
                     (const VariableCharacteristicsType   *message);
size_t variable_characteristics_type__pack
                     (const VariableCharacteristicsType   *message,
                      uint8_t             *out);
size_t variable_characteristics_type__pack_to_buffer
                     (const VariableCharacteristicsType   *message,
                      ProtobufCBuffer     *buffer);
VariableCharacteristicsType *
       variable_characteristics_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   variable_characteristics_type__free_unpacked
                     (VariableCharacteristicsType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*VariableCharacteristicsType_Closure)
                 (const VariableCharacteristicsType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor variable_characteristics_type__descriptor;
extern const ProtobufCEnumDescriptor    variable_characteristics_type__date_enum_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_variableCharacteristicsType_2eproto__INCLUDED */
